server:
  servlet:
    context-path: /e-process
  port: 8080
---
management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints (e.g., health, metrics, etc.)
  endpoint:
    health:
      show-details: always # Show detailed health information
    prometheus:
      enabled: true
  metrics:
    tags:
      application: e-process-service
---
spring:
  application:
    name: e-process-service
  profiles:
    active: ${PROFILE:local}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true #SQL format for readability
        use_sql_comments: true #add comment into SQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 30
          fetch_size: 50
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${spring.application.name}
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  flyway:
    enabled: false
    schemas: e-process-service

  cloud:
    function:
      definition: workflowCanceledConsumer
    stream:
      bindings:
        workflowCanceledConsumer-in-0:
          destination: workflow.canceled
          group: e-process-service
      rabbit:
        bindings:
          workflowCanceledConsumer-in-0:
            consumer:
              binding-routing-key: "workflow.canceled.e-process"
---
security:
  service-key: 11ecde83-1597-454b-91c6-db37b4dc1156
---
app-feign:
  connection-timeout: 5000
  read-timeout: 10000
---
api:
  info:
    title: EProcess Service API
    version: 1.0.0
    description: API documentation for EProcess Microservice