server:
  port: 8086
---
spring:
  config:
    import: "optional:configserver:instead"
  datasource:
    url: jdbc:postgresql://localhost:5432/operations_db
    username: postgres
    password: postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
---
app-feign:
  services:
    document: http://localhost:8083
    workflow: http://localhost:8084
    authentication: http://localhost:8082
